export enum Position {
  INTERN = 'INTERN',
  SPECIALIST = 'SPECIALIST',
  SENIOR_SPECIALIST = 'SENIOR_SPECIALIST',
  TEAM_LEAD = 'TEAM_LEAD',
  MANAGER = 'MANAGER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  DIRECTOR = 'DIRECTOR'
}
